volumes:
  vote_classifier: {}

networks:
  vote_classifier:


services:
  django:
    build: .
    container_name: voter_backend
    ports:
      - 9494:8000
    environment:
      DEBUG: "True"
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_HOSTS: localhost,127.0.0.1,django
    volumes:
      - vote_classifier:/app/data
    stdin_open: true
    tty: true
    networks:
      - vote_classifier
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./compose/nginx/Dockerfile
  #   image: vote_classifier
  #   depends_on:
  #     - django
  #   volumes:
  #     - vote_classifier:/app/media
  #   ports:
  #     - 9494:80
  #   networks:
  #     - vote_classifier
  #   restart: always
