version: "3.8"

services:
  web:
    build: .
    container_name: voter_analysis_api
    ports:
      - "9494:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_HOSTS: localhost,127.0.0.1
    volumes:
      - vote_classifier:/app/data   
    stdin_open: true
    tty: true

volumes:
  voter_data:

