# Generated by Django 5.0.1 on 2026-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.CharField(blank=True, db_index=True, help_text='Constituency/Area name (derived from filename)', max_length=100, null=True),
        ),
    ]
